# Generated by Django 5.0.1 on 2024-01-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companie', '0002_remove_companies_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companie.location'),
        ),
    ]
